# Generated by Django 3.1.5 on 2021-01-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description_short', models.TextField(max_length=1000)),
                ('description_long', models.TextField()),
                ('lng', models.DecimalField(decimal_places=14, max_digits=17)),
                ('lat', models.DecimalField(decimal_places=14, max_digits=17)),
            ],
        ),
    ]
