# Generated by Django 3.1.5 on 2021-03-10 11:09

import uuid

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название для боковой панели')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('long_description', tinymce.models.HTMLField(blank=True, verbose_name='Полное описание')),
                ('lng', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('properties_title',
                 models.CharField(default='', max_length=200, verbose_name='Название точки на карте')),
                ('properties_placeId',
                 models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Уникальный идентификатор локации')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Позиция в списке')),
                ('image', models.ImageField(upload_to='', verbose_name='Файл')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images',
                                               to='places.location', verbose_name='Место')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
