# Generated by Django 3.1.5 on 2021-03-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='order',
        ),
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.SmallIntegerField(db_index=True, default=0, verbose_name='Позиция в списке'),
        ),
    ]
