# Generated by Django 3.1.5 on 2021-03-18 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0002_auto_20210310_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='properties_placeId',
            new_name='identifier',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='properties_title',
            new_name='map_title',
        ),
    ]
