# Generated by Django 3.1.5 on 2021-01-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='order_no',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
