# Generated by Django 3.1.5 on 2021-03-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0003_auto_20210318_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='map_title',
            field=models.CharField(max_length=200, verbose_name='Название точки на карте'),
        ),
    ]
