# Generated by Django 3.1.5 on 2021-02-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_image_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='properties_placeId',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='properties_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
