# Generated by Django 3.1.5 on 2021-02-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20210202_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='image',
            name='order_no',
            field=models.SmallIntegerField(verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description_long',
            field=models.TextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description_short',
            field=models.TextField(max_length=1000, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.CharField(max_length=30, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.CharField(max_length=30, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='location',
            name='properties_title',
            field=models.CharField(default='', max_length=200, verbose_name='Название точки на карте'),
        ),
    ]
