# Generated by Django 3.1.5 on 2021-02-08 06:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20210207_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description_long',
            field=tinymce.models.HTMLField(max_length=1000, verbose_name='Полное описание'),
        ),
    ]
