# Generated by Django 3.1.5 on 2021-02-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_auto_20210208_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description_short',
            field=models.TextField(max_length=5000, verbose_name='Краткое описание'),
        ),
    ]
