# Generated by Django 3.1.5 on 2021-02-08 06:51

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_auto_20210208_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description_long',
            field=tinymce.models.HTMLField(max_length=5000, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description_short',
            field=models.TextField(max_length=1000, verbose_name='Краткое описание'),
        ),
    ]
