# Generated by Django 3.1.5 on 2021-02-12 17:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_auto_20210208_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description_long',
            field=tinymce.models.HTMLField(max_length=10000, verbose_name='Полное описание'),
        ),
    ]
