# Generated by Django 3.1.5 on 2021-02-19 13:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_auto_20210212_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description_short',
            field=models.CharField(max_length=1000, verbose_name='Краткое описание'),
        ),
    ]
