# Generated by Django 3.1.5 on 2021-02-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_auto_20210219_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
