# Generated by Django 3.1.5 on 2021-02-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_auto_20210219_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='short_description',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
    ]
