# Generated by Django 3.1.5 on 2021-02-20 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_auto_20210219_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название для боковой панели'),
        ),
    ]
