# Generated by Django 3.1.5 on 2021-02-20 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0020_auto_20210220_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc_imgs', to='places.location'),
        ),
    ]
